### ISSUE TITLE
Strange Emmet Behavior

### ISSUE THREAD

**Issue by awsp** [c9/c9.ide.ace.emmet#1]
Apologize if this is the wrong place to report this issue. I found this plugin installed from c9 plugin manager. 

Just finish installing the [Cloud9 3.0 SDK](https://github.com/c9/core/). 
When typing for example, `h2.foo`, the editor gives me `<div class="foo"></div>` where it is supposed to return `<h2 class="foo"></h2>`

Also some of the HTML5 tags such as `article`, `section` were not expanding at all. 

But `h2.foo` as well as  HTML5 tags work when trying from the following URL but not the SDK nor the actual ace.c9.io editor.
http://ace.c9.io/demo/emmet.html

**Comment by nightwing** [comment]
Emmet dependency was missing from package.json. I've created pull request adding it, but until that is merged  `npm i "git://github.com/cloud9ide/emmet-core.git#2ff6dc06ad037357fe19a52e23effeb08a8dc1d6"` should fix the issue.

**Comment by nightwing** [comment]
This is fixed now, please comment if you still see the issue.
